# Generated by Django 4.1.7 on 2023-03-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirante',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
