# Generated by Django 4.1.7 on 2023-03-04 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0002_alter_aspirante_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirante',
            name='grimorio',
            field=models.ForeignKey(auto_created=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Registro.grimorios'),
        ),
    ]
