# Generated by Django 4.1.7 on 2023-03-04 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0003_alter_aspirante_grimorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirante',
            name='grimorio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Registro.grimorios'),
        ),
    ]
